# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message_queue.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='message_queue.proto',
  package='messagequeue',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x13message_queue.proto\x12\x0cmessagequeue\"W\n\x0bSendRequest\x12\x14\n\x0cservice_name\x18\x01 \x01(\t\x12\x11\n\tfunc_name\x18\x02 \x01(\t\x12\x0e\n\x06msg_id\x18\x03 \x01(\t\x12\x0f\n\x07payload\x18\x04 \x01(\t\"\x1e\n\x0cSendResponse\x12\x0e\n\x06msg_id\x18\x01 \x01(\t\"Z\n\x0eReceiveRequest\x12\x14\n\x0cservice_name\x18\x01 \x01(\t\x12\x11\n\tfunc_name\x18\x02 \x01(\t\x12\x0e\n\x06msg_id\x18\x03 \x01(\t\x12\x0f\n\x07timeout\x18\x04 \x01(\x05\"2\n\x0fReceiveResponse\x12\x0f\n\x07payload\x18\x01 \x01(\t\x12\x0e\n\x06msg_id\x18\x02 \x01(\t\"E\n\nGetRequest\x12\x14\n\x0cservice_name\x18\x01 \x01(\t\x12\x11\n\tfunc_name\x18\x02 \x01(\t\x12\x0e\n\x06msg_id\x18\x03 \x01(\t\".\n\x0bGetResponse\x12\x0f\n\x07payload\x18\x01 \x01(\x08\x12\x0e\n\x06msg_id\x18\x02 \x01(\t\"^\n\x12\x41\x63knowledgeRequest\x12\x14\n\x0cservice_name\x18\x01 \x01(\t\x12\x11\n\tfunc_name\x18\x02 \x01(\t\x12\x0e\n\x06msg_id\x18\x03 \x01(\t\x12\x0f\n\x07payload\x18\x04 \x01(\t\"&\n\x13\x41\x63knowledgeResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\xd6\x04\n\x0cMessageQueue\x12\x43\n\x08send_msg\x12\x19.messagequeue.SendRequest\x1a\x1a.messagequeue.SendResponse\"\x00\x12I\n\x08recv_rsp\x12\x1c.messagequeue.ReceiveRequest\x1a\x1d.messagequeue.ReceiveResponse\"\x00\x12@\n\x07get_rsp\x12\x18.messagequeue.GetRequest\x1a\x19.messagequeue.GetResponse\"\x00\x12P\n\x07\x61\x63k_rsp\x12 .messagequeue.AcknowledgeRequest\x1a!.messagequeue.AcknowledgeResponse\"\x00\x12I\n\x08recv_msg\x12\x1c.messagequeue.ReceiveRequest\x1a\x1d.messagequeue.ReceiveResponse\"\x00\x12@\n\x07get_msg\x12\x18.messagequeue.GetRequest\x1a\x19.messagequeue.GetResponse\"\x00\x12P\n\x07\x61\x63k_msg\x12 .messagequeue.AcknowledgeRequest\x1a!.messagequeue.AcknowledgeResponse\"\x00\x12\x43\n\x08send_rsp\x12\x19.messagequeue.SendRequest\x1a\x1a.messagequeue.SendResponse\"\x00\x62\x06proto3')
)




_SENDREQUEST = _descriptor.Descriptor(
  name='SendRequest',
  full_name='messagequeue.SendRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='service_name', full_name='messagequeue.SendRequest.service_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='func_name', full_name='messagequeue.SendRequest.func_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='msg_id', full_name='messagequeue.SendRequest.msg_id', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='payload', full_name='messagequeue.SendRequest.payload', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=37,
  serialized_end=124,
)


_SENDRESPONSE = _descriptor.Descriptor(
  name='SendResponse',
  full_name='messagequeue.SendResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='msg_id', full_name='messagequeue.SendResponse.msg_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=126,
  serialized_end=156,
)


_RECEIVEREQUEST = _descriptor.Descriptor(
  name='ReceiveRequest',
  full_name='messagequeue.ReceiveRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='service_name', full_name='messagequeue.ReceiveRequest.service_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='func_name', full_name='messagequeue.ReceiveRequest.func_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='msg_id', full_name='messagequeue.ReceiveRequest.msg_id', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timeout', full_name='messagequeue.ReceiveRequest.timeout', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=158,
  serialized_end=248,
)


_RECEIVERESPONSE = _descriptor.Descriptor(
  name='ReceiveResponse',
  full_name='messagequeue.ReceiveResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='payload', full_name='messagequeue.ReceiveResponse.payload', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='msg_id', full_name='messagequeue.ReceiveResponse.msg_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=250,
  serialized_end=300,
)


_GETREQUEST = _descriptor.Descriptor(
  name='GetRequest',
  full_name='messagequeue.GetRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='service_name', full_name='messagequeue.GetRequest.service_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='func_name', full_name='messagequeue.GetRequest.func_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='msg_id', full_name='messagequeue.GetRequest.msg_id', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=302,
  serialized_end=371,
)


_GETRESPONSE = _descriptor.Descriptor(
  name='GetResponse',
  full_name='messagequeue.GetResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='payload', full_name='messagequeue.GetResponse.payload', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='msg_id', full_name='messagequeue.GetResponse.msg_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=373,
  serialized_end=419,
)


_ACKNOWLEDGEREQUEST = _descriptor.Descriptor(
  name='AcknowledgeRequest',
  full_name='messagequeue.AcknowledgeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='service_name', full_name='messagequeue.AcknowledgeRequest.service_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='func_name', full_name='messagequeue.AcknowledgeRequest.func_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='msg_id', full_name='messagequeue.AcknowledgeRequest.msg_id', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='payload', full_name='messagequeue.AcknowledgeRequest.payload', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=421,
  serialized_end=515,
)


_ACKNOWLEDGERESPONSE = _descriptor.Descriptor(
  name='AcknowledgeResponse',
  full_name='messagequeue.AcknowledgeResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='messagequeue.AcknowledgeResponse.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=517,
  serialized_end=555,
)

DESCRIPTOR.message_types_by_name['SendRequest'] = _SENDREQUEST
DESCRIPTOR.message_types_by_name['SendResponse'] = _SENDRESPONSE
DESCRIPTOR.message_types_by_name['ReceiveRequest'] = _RECEIVEREQUEST
DESCRIPTOR.message_types_by_name['ReceiveResponse'] = _RECEIVERESPONSE
DESCRIPTOR.message_types_by_name['GetRequest'] = _GETREQUEST
DESCRIPTOR.message_types_by_name['GetResponse'] = _GETRESPONSE
DESCRIPTOR.message_types_by_name['AcknowledgeRequest'] = _ACKNOWLEDGEREQUEST
DESCRIPTOR.message_types_by_name['AcknowledgeResponse'] = _ACKNOWLEDGERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SendRequest = _reflection.GeneratedProtocolMessageType('SendRequest', (_message.Message,), dict(
  DESCRIPTOR = _SENDREQUEST,
  __module__ = 'message_queue_pb2'
  # @@protoc_insertion_point(class_scope:messagequeue.SendRequest)
  ))
_sym_db.RegisterMessage(SendRequest)

SendResponse = _reflection.GeneratedProtocolMessageType('SendResponse', (_message.Message,), dict(
  DESCRIPTOR = _SENDRESPONSE,
  __module__ = 'message_queue_pb2'
  # @@protoc_insertion_point(class_scope:messagequeue.SendResponse)
  ))
_sym_db.RegisterMessage(SendResponse)

ReceiveRequest = _reflection.GeneratedProtocolMessageType('ReceiveRequest', (_message.Message,), dict(
  DESCRIPTOR = _RECEIVEREQUEST,
  __module__ = 'message_queue_pb2'
  # @@protoc_insertion_point(class_scope:messagequeue.ReceiveRequest)
  ))
_sym_db.RegisterMessage(ReceiveRequest)

ReceiveResponse = _reflection.GeneratedProtocolMessageType('ReceiveResponse', (_message.Message,), dict(
  DESCRIPTOR = _RECEIVERESPONSE,
  __module__ = 'message_queue_pb2'
  # @@protoc_insertion_point(class_scope:messagequeue.ReceiveResponse)
  ))
_sym_db.RegisterMessage(ReceiveResponse)

GetRequest = _reflection.GeneratedProtocolMessageType('GetRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETREQUEST,
  __module__ = 'message_queue_pb2'
  # @@protoc_insertion_point(class_scope:messagequeue.GetRequest)
  ))
_sym_db.RegisterMessage(GetRequest)

GetResponse = _reflection.GeneratedProtocolMessageType('GetResponse', (_message.Message,), dict(
  DESCRIPTOR = _GETRESPONSE,
  __module__ = 'message_queue_pb2'
  # @@protoc_insertion_point(class_scope:messagequeue.GetResponse)
  ))
_sym_db.RegisterMessage(GetResponse)

AcknowledgeRequest = _reflection.GeneratedProtocolMessageType('AcknowledgeRequest', (_message.Message,), dict(
  DESCRIPTOR = _ACKNOWLEDGEREQUEST,
  __module__ = 'message_queue_pb2'
  # @@protoc_insertion_point(class_scope:messagequeue.AcknowledgeRequest)
  ))
_sym_db.RegisterMessage(AcknowledgeRequest)

AcknowledgeResponse = _reflection.GeneratedProtocolMessageType('AcknowledgeResponse', (_message.Message,), dict(
  DESCRIPTOR = _ACKNOWLEDGERESPONSE,
  __module__ = 'message_queue_pb2'
  # @@protoc_insertion_point(class_scope:messagequeue.AcknowledgeResponse)
  ))
_sym_db.RegisterMessage(AcknowledgeResponse)



_MESSAGEQUEUE = _descriptor.ServiceDescriptor(
  name='MessageQueue',
  full_name='messagequeue.MessageQueue',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=558,
  serialized_end=1156,
  methods=[
  _descriptor.MethodDescriptor(
    name='send_msg',
    full_name='messagequeue.MessageQueue.send_msg',
    index=0,
    containing_service=None,
    input_type=_SENDREQUEST,
    output_type=_SENDRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='recv_rsp',
    full_name='messagequeue.MessageQueue.recv_rsp',
    index=1,
    containing_service=None,
    input_type=_RECEIVEREQUEST,
    output_type=_RECEIVERESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='get_rsp',
    full_name='messagequeue.MessageQueue.get_rsp',
    index=2,
    containing_service=None,
    input_type=_GETREQUEST,
    output_type=_GETRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ack_rsp',
    full_name='messagequeue.MessageQueue.ack_rsp',
    index=3,
    containing_service=None,
    input_type=_ACKNOWLEDGEREQUEST,
    output_type=_ACKNOWLEDGERESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='recv_msg',
    full_name='messagequeue.MessageQueue.recv_msg',
    index=4,
    containing_service=None,
    input_type=_RECEIVEREQUEST,
    output_type=_RECEIVERESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='get_msg',
    full_name='messagequeue.MessageQueue.get_msg',
    index=5,
    containing_service=None,
    input_type=_GETREQUEST,
    output_type=_GETRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ack_msg',
    full_name='messagequeue.MessageQueue.ack_msg',
    index=6,
    containing_service=None,
    input_type=_ACKNOWLEDGEREQUEST,
    output_type=_ACKNOWLEDGERESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='send_rsp',
    full_name='messagequeue.MessageQueue.send_rsp',
    index=7,
    containing_service=None,
    input_type=_SENDREQUEST,
    output_type=_SENDRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_MESSAGEQUEUE)

DESCRIPTOR.services_by_name['MessageQueue'] = _MESSAGEQUEUE

# @@protoc_insertion_point(module_scope)
